name: Build and Scan App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: woulf/portfolio

jobs:
  build_push_image:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get short SHA
        id: sha
        run: echo "sha_short=$(echo $GITHUB_SHA | cut -c1-7)" >> "$GITHUB_OUTPUT"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image (local only)
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true # Charge l’image localement, mais ne la push pas
          tags: ${{ env.IMAGE_NAME }}:temp-${{ steps.sha.outputs.sha_short }}
          secrets: |
            "devto_token=${{ secrets.DEVTO_API_KEY }}"
  
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:temp-${{ steps.sha.outputs.sha_short }}
          format: table
          severity: CRITICAL,HIGH
          exit-code: 1

      - name: Push image with temp tag
        run: docker push ${{ env.IMAGE_NAME }}:temp-${{ steps.sha.outputs.sha_short }}
