name: Deploy RC

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  IMAGE_NAME: woulf/portfolio

jobs:
  tag_image:
    name: Tag & Push rc with tag version
    runs-on: ubuntu-latest

    steps:
      - name: Extract tag without "v"
        id: version
        run: |
          RAW_TAG="${GITHUB_REF##refs/tags/}"
          CLEAN_TAG="${RAW_TAG#v}"
          echo "clean_tag=$CLEAN_TAG" >> "$GITHUB_OUTPUT"

      - name: Get short SHA
        id: sha
        run: echo "sha_short=$(echo $GITHUB_SHA | cut -c1-7)" >> "$GITHUB_OUTPUT"
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull temp image
        run: docker pull ${{ env.IMAGE_NAME }}:temp-${{ steps.sha.outputs.sha_short }}

      - name: Tag image as X.Y.Z-rc
        run: docker tag ${{ env.IMAGE_NAME }}:temp-${{ steps.sha.outputs.sha_short }} ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.clean_tag }}-rc

      - name: Push tag
        run: docker push ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.clean_tag }}-rc
