name: Deploy Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NAMESPACE: default
  DEPLOYMENT_NAME: portfolio

jobs:
  build_push_image:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image (local only)
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true # Charge l’image localement, mais ne la push pas
          tags: woulf/portfolio:latest
          secrets: |
            "devto_token=${{ secrets.DEVTO_API_KEY }}"
  
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: woulf/portfolio:latest
          format: table
          severity: CRITICAL,HIGH
          exit-code: 1
  
      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: woulf/portfolio:latest
          secrets: |
            "devto_token=${{ secrets.DEVTO_API_KEY }}"

  rollout_k8s:
    name: Restart Kubernetes Deployment
    runs-on: ubuntu-latest
    needs: build_push_image

    steps:
      - name: Set up Kubernetes context
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Restart Deployment
        run: |
          kubectl rollout restart deployment/${{ env.DEPLOYMENT_NAME }} -n ${{ env.NAMESPACE }}
          kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }} -n ${{ env.NAMESPACE }}
